name: build-and-test

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup project
        run: npm install 
        
      - name: Lint check
        run: make lint

      - name: Testing
        run: make test

      - name: Coverage
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODE_COVERAGE_TEST_REPORT_ID }}
        with:
          coverageCommand: make coverage
